// Research fixture: native capture -> ordered browser-to-Node chunks -> partial file.
// Run only against the local synthetic scene generated by bench.cjs.
const fs = require('node:fs/promises');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { randomUUID } = require('node:crypto');
const { execFileSync } = require('node:child_process');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');

const root = process.env.CAPTURE_BENCH_DIR || '/tmp/astrocade-capture-bench';
const executablePath = process.env.CHROME_EXECUTABLE || chromium.executablePath();
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
async function bounded(promise, milliseconds, label) {
  let timer;
  try {
    return await Promise.race([promise, new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error(`${label} exceeded ${milliseconds} ms`)), milliseconds);
    })]);
  } finally { clearTimeout(timer); }
}
async function exists(file) { try { await fs.access(file); return true; } catch { return false; } }

function inspect(file) {
  const ffprobe = process.env.FFPROBE_PATH || 'ffprobe';
  const ffmpeg = process.env.FFMPEG_PATH || 'ffmpeg';
  const probe = JSON.parse(execFileSync(ffprobe, ['-v', 'error', '-show_entries', 'format=size:stream=codec_name,width,height', '-of', 'json', file], { encoding: 'utf8', timeout: 10000 }));
  const pts = JSON.parse(execFileSync(ffprobe, ['-v', 'error', '-select_streams', 'v:0', '-show_entries', 'packet=pts_time', '-of', 'json', file], { encoding: 'utf8', timeout: 10000 })).packets.map(p => Number(p.pts_time)).sort((a, b) => a - b);
  const raw = execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-xerror', '-i', file, '-vf', 'crop=600:40:20:130,format=gray', '-fps_mode', 'passthrough', '-f', 'rawvideo', 'pipe:1'], { maxBuffer: 20 * 1024 * 1024, timeout: 15000 });
  const ids = [];
  for (let p = 0; p < raw.length; p += 24000) {
    let id = 0;
    for (let bit = 0; bit < 12; bit++) if (raw[p + 12000 + bit * 50 + 20] > 128) id |= 1 << bit;
    ids.push(id);
  }
  return { probe, decodedFrames: ids.length, distinctSceneIds: new Set(ids).size, firstPts: pts[0], lastPts: pts.at(-1), actualPacketRate: (pts.length - 1) / (pts.at(-1) - pts[0]), completeDecode: true };
}

async function attempt(cancel) {
  // Allocate the token before launch: Chromium's selection switch is process-scoped.
  const token = `AstroCapture-${randomUUID()}`;
  const label = cancel ? 'cancel' : 'normal';
  const partial = path.join(root, `incremental-${label}-${token}.partial.webm`);
  const ready = path.join(root, `incremental-${label}-${token}.webm`);
  const handle = await fs.open(partial, 'wx');
  let handleClosed = false;
  const browser = await chromium.launch({ headless: true, executablePath, args: [`--auto-select-tab-capture-source-by-title=${token}`] });
  const runtime = { browser: browser.version(), playwright: require(require.resolve('playwright/package.json', { paths: [process.env.PLAYWRIGHT_MODULE_PATH || process.cwd()] })).version };
  let bytes = 0;
  const appendedSequences = [];
  let inFlightWrites = 0;
  let resolveFirstWrite;
  const firstWriteStarted = new Promise(resolve => { resolveFirstWrite = resolve; });
  let lastWrite = Promise.resolve();
  let outcome;
  try {
    const game = await browser.newPage({ viewport: { width: 1080, height: 1920 }, deviceScaleFactor: 1 });
    await game.goto(pathToFileURL(path.join(root, 'scene.html')).href);
    await game.evaluate(title => { document.title = title; }, token);
    const recorder = await browser.newPage({ viewport: { width: 800, height: 600 } });
    await recorder.goto(pathToFileURL(path.join(root, 'scene.html')).href);
    await recorder.evaluate(() => { document.title = 'Local recorder'; });
    await recorder.exposeBinding('writeCaptureChunk', async (_source, payload) => {
      if (payload.sequence !== appendedSequences.length) throw new Error('Chunk sequence is not contiguous');
      const data = Buffer.from(payload.base64, 'base64');
      if (data.length > 16 * 1024 * 1024) throw new Error('Chunk exceeds research buffer limit');
      inFlightWrites++;
      resolveFirstWrite();
      const write = (async () => {
        // Deliberately exercise cancellation while the first append is still pending.
        if (cancel) await sleep(500);
        await handle.writeFile(data);
        bytes += data.length;
        appendedSequences.push(payload.sequence);
      })();
      lastWrite = write;
      try { await write; } finally { inFlightWrites--; }
    });
    await recorder.evaluate(() => {
      window.captureError = null;
      window.captureReady = false;
      window.captureStats = { receivedChunks: 0, pendingBytes: 0, maximumPendingBytes: 0 };
      window.uploadTail = Promise.resolve();
      const button = document.createElement('button');
      button.textContent = 'Start capture';
      button.style = 'position:fixed;left:0;top:0';
      document.body.append(button);
      button.onclick = async () => {
        try {
          const stream = await navigator.mediaDevices.getDisplayMedia({ video: { displaySurface: 'browser', frameRate: 30, width: 1080, height: 1920 }, audio: false });
          window.captureStream = stream;
          const media = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp9', videoBitsPerSecond: 8000000 });
          window.mediaRecorder = media;
          window.stopped = new Promise(resolve => media.addEventListener('stop', resolve, { once: true }));
          media.onerror = event => { window.captureError = String(event.error || 'MediaRecorder error'); };
          media.ondataavailable = event => {
            if (!event.data.size) return;
            const sequence = window.captureStats.receivedChunks++;
            const data = event.data;
            window.captureStats.pendingBytes += data.size;
            window.captureStats.maximumPendingBytes = Math.max(window.captureStats.maximumPendingBytes, window.captureStats.pendingBytes);
            if (window.captureStats.pendingBytes > 16 * 1024 * 1024) {
              window.captureError = 'Chunk backlog exceeded research limit';
              if (media.state !== 'inactive') media.stop();
              return;
            }
            window.uploadTail = window.uploadTail.then(async () => {
              const base64 = await new Promise((resolve, reject) => {
                const reader = new FileReader();
                reader.onerror = () => reject(reader.error);
                reader.onload = () => resolve(String(reader.result).split(',')[1]);
                reader.readAsDataURL(data);
              });
              await window.writeCaptureChunk({ sequence, base64 });
              window.captureStats.pendingBytes -= data.size;
            }).catch(error => {
              window.captureError = String(error);
              if (media.state !== 'inactive') media.stop();
            });
          };
          window.finishCapture = async () => {
            const beforeStopChunks = window.captureStats.receivedChunks;
            try {
              if (media.state !== 'inactive') media.stop();
              await window.stopped;
              await window.uploadTail;
              if (window.captureError) throw new Error(window.captureError);
              return { beforeStopChunks, ...window.captureStats, recorderState: media.state };
            } finally { stream.getTracks().forEach(track => track.stop()); }
          };
          button.remove();
          media.start(1000);
          window.captureReady = true;
        } catch (error) { window.captureError = String(error); }
      };
    });
    await recorder.getByRole('button', { name: 'Start capture' }).click();
    await recorder.waitForFunction(() => window.captureReady || window.captureError, {}, { timeout: 10000 });
    const startup = await recorder.evaluate(() => ({ error: window.captureError, settings: window.captureStream?.getVideoTracks()[0].getSettings() }));
    if (startup.error) throw new Error(startup.error);
    await game.bringToFront();
    await game.evaluate(() => window.go());
    if (cancel) await bounded(firstWriteStarted, 5000, 'first chunk');
    else await sleep(3400);
    const writesInFlightWhenStopped = inFlightWrites;
    await game.evaluate(() => window.stop());
    const flush = await bounded(recorder.evaluate(() => window.finishCapture()), 10000, 'recorder finish');
    const trackStates = await recorder.evaluate(() => window.captureStream.getTracks().map(track => track.readyState));
    await lastWrite;
    await handle.close();
    handleClosed = true;
    const beforePromotion = { readyExists: await exists(ready), partialExists: await exists(partial) };
    if (beforePromotion.readyExists || !beforePromotion.partialExists) throw new Error('Unexpected file state');
    let measurement;
    if (!cancel) {
      measurement = inspect(partial);
      if (!measurement.decodedFrames || measurement.probe.streams[0].codec_name !== 'vp9') throw new Error('Incomplete capture');
      await fs.rename(partial, ready);
    }
    outcome = { label, token, runtime, startup, bytes, appendedSequences, writesInFlightWhenStopped, flush, trackStates, beforePromotion, measurement };
  } finally {
    await browser.close();
    await lastWrite.catch(() => {});
    if (!handleClosed) await handle.close();
    if (cancel) await fs.rm(partial, { force: true });
  }
  outcome.afterBrowserStopped = { readyExists: await exists(ready), partialExists: await exists(partial) };
  if (cancel && (outcome.afterBrowserStopped.readyExists || outcome.afterBrowserStopped.partialExists)) throw new Error('Canceled attempt left a capture artifact');
  return outcome;
}

(async () => {
  await fs.mkdir(root, { recursive: true });
  const result = { researchedAt: '2026-10-06', note: 'Synthetic local fixture. Normal stop + final chunk flushing and cancellation during an outstanding append. Not a crash/disk-full/live-Astrocade test.', attempts: [await attempt(false), await attempt(true)] };
  await fs.writeFile(path.join(root, 'incremental-result.json'), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
})().catch(error => { console.error(error); process.exitCode = 1; });
